// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Market struct {
	BaseAsset       string
	QuoteAsset      string
	BaseDecimals    int64
	QuoteDecimals   int64
	MinQuoteAmount  int64
	MaxQuoteAmount  int64
	MinBaseAmount   int64
	MaxBaseAmount   int64
	PriceFeed       string
	ToleranceBps    int64
	FeeBps          int64
	PricePath       string
	PriceTtlSeconds int64
}

type Trade struct {
	ID            int64
	Market        string
	DepositAsset  string
	DepositAmount int64
	WantAsset     string
	WantAmount    int64
	OfferTxid     string
	FulfillTxid   string
	CreatedAt     int64
	Error         string
}
