// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type BancoPair struct {
	Pair          string
	MinAmount     int64
	MaxAmount     int64
	BaseDecimals  int64
	QuoteDecimals int64
	PriceFeed     string
	InvertPrice   int64
}

type Trade struct {
	ID            int64
	Pair          string
	DepositAsset  string
	DepositAmount int64
	WantAsset     string
	WantAmount    int64
	OfferTxid     string
	FulfillTxid   string
	CreatedAt     int64
}
