// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
)

const deleteMarket = `-- name: DeleteMarket :exec
DELETE FROM market WHERE base_asset = ? AND quote_asset = ?
`

type DeleteMarketParams struct {
	BaseAsset  string
	QuoteAsset string
}

func (q *Queries) DeleteMarket(ctx context.Context, arg DeleteMarketParams) error {
	_, err := q.db.ExecContext(ctx, deleteMarket, arg.BaseAsset, arg.QuoteAsset)
	return err
}

const insertMarket = `-- name: InsertMarket :exec
INSERT INTO market (base_asset, quote_asset, base_decimals, quote_decimals, min_quote_amount, max_quote_amount, min_base_amount, max_base_amount, price_feed, price_path, slippage_bps, fee_bps, price_ttl_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMarketParams struct {
	BaseAsset       string
	QuoteAsset      string
	BaseDecimals    int64
	QuoteDecimals   int64
	MinQuoteAmount  int64
	MaxQuoteAmount  int64
	MinBaseAmount   int64
	MaxBaseAmount   int64
	PriceFeed       string
	PricePath       string
	SlippageBps     int64
	FeeBps          int64
	PriceTtlSeconds int64
}

func (q *Queries) InsertMarket(ctx context.Context, arg InsertMarketParams) error {
	_, err := q.db.ExecContext(ctx, insertMarket,
		arg.BaseAsset,
		arg.QuoteAsset,
		arg.BaseDecimals,
		arg.QuoteDecimals,
		arg.MinQuoteAmount,
		arg.MaxQuoteAmount,
		arg.MinBaseAmount,
		arg.MaxBaseAmount,
		arg.PriceFeed,
		arg.PricePath,
		arg.SlippageBps,
		arg.FeeBps,
		arg.PriceTtlSeconds,
	)
	return err
}

const insertTrade = `-- name: InsertTrade :exec
INSERT INTO trade (market, deposit_asset, deposit_amount, want_asset, want_amount, offer_txid, fulfill_txid, error, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTradeParams struct {
	Market        string
	DepositAsset  string
	DepositAmount int64
	WantAsset     string
	WantAmount    int64
	OfferTxid     string
	FulfillTxid   string
	Error         string
	CreatedAt     int64
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) error {
	_, err := q.db.ExecContext(ctx, insertTrade,
		arg.Market,
		arg.DepositAsset,
		arg.DepositAmount,
		arg.WantAsset,
		arg.WantAmount,
		arg.OfferTxid,
		arg.FulfillTxid,
		arg.Error,
		arg.CreatedAt,
	)
	return err
}

const listMarkets = `-- name: ListMarkets :many
SELECT base_asset, quote_asset, base_decimals, quote_decimals, min_quote_amount, max_quote_amount, min_base_amount, max_base_amount, price_feed, slippage_bps, fee_bps, price_path, price_ttl_seconds FROM market
`

func (q *Queries) ListMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.QueryContext(ctx, listMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.BaseDecimals,
			&i.QuoteDecimals,
			&i.MinQuoteAmount,
			&i.MaxQuoteAmount,
			&i.MinBaseAmount,
			&i.MaxBaseAmount,
			&i.PriceFeed,
			&i.SlippageBps,
			&i.FeeBps,
			&i.PricePath,
			&i.PriceTtlSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
SELECT id, market, deposit_asset, deposit_amount, want_asset, want_amount, offer_txid, fulfill_txid, created_at, error FROM trade
WHERE (
  CAST(?1 AS TEXT) = ''
  OR (CAST(?1 AS TEXT) = 'failed' AND error != '')
  OR (CAST(?1 AS TEXT) = 'succeeded' AND error = '')
)
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListTradesParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTrades, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.DepositAsset,
			&i.DepositAmount,
			&i.WantAsset,
			&i.WantAmount,
			&i.OfferTxid,
			&i.FulfillTxid,
			&i.CreatedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarket = `-- name: UpdateMarket :execrows
UPDATE market
SET base_decimals = ?, quote_decimals = ?, min_quote_amount = ?, max_quote_amount = ?, min_base_amount = ?, max_base_amount = ?, price_feed = ?, price_path = ?, slippage_bps = ?, fee_bps = ?, price_ttl_seconds = ?
WHERE base_asset = ? AND quote_asset = ?
`

type UpdateMarketParams struct {
	BaseDecimals    int64
	QuoteDecimals   int64
	MinQuoteAmount  int64
	MaxQuoteAmount  int64
	MinBaseAmount   int64
	MaxBaseAmount   int64
	PriceFeed       string
	PricePath       string
	SlippageBps     int64
	FeeBps          int64
	PriceTtlSeconds int64
	BaseAsset       string
	QuoteAsset      string
}

func (q *Queries) UpdateMarket(ctx context.Context, arg UpdateMarketParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarket,
		arg.BaseDecimals,
		arg.QuoteDecimals,
		arg.MinQuoteAmount,
		arg.MaxQuoteAmount,
		arg.MinBaseAmount,
		arg.MaxBaseAmount,
		arg.PriceFeed,
		arg.PricePath,
		arg.SlippageBps,
		arg.FeeBps,
		arg.PriceTtlSeconds,
		arg.BaseAsset,
		arg.QuoteAsset,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
