// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
)

const deletePair = `-- name: DeletePair :exec
DELETE FROM banco_pair WHERE pair = ?
`

func (q *Queries) DeletePair(ctx context.Context, pair string) error {
	_, err := q.db.ExecContext(ctx, deletePair, pair)
	return err
}

const insertPair = `-- name: InsertPair :exec
INSERT INTO banco_pair (pair, min_amount, max_amount, base_decimals, quote_decimals, price_feed, invert_price)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPairParams struct {
	Pair          string
	MinAmount     int64
	MaxAmount     int64
	BaseDecimals  int64
	QuoteDecimals int64
	PriceFeed     string
	InvertPrice   int64
}

func (q *Queries) InsertPair(ctx context.Context, arg InsertPairParams) error {
	_, err := q.db.ExecContext(ctx, insertPair,
		arg.Pair,
		arg.MinAmount,
		arg.MaxAmount,
		arg.BaseDecimals,
		arg.QuoteDecimals,
		arg.PriceFeed,
		arg.InvertPrice,
	)
	return err
}

const insertTrade = `-- name: InsertTrade :exec
INSERT INTO trade (pair, deposit_asset, deposit_amount, want_asset, want_amount, offer_txid, fulfill_txid, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTradeParams struct {
	Pair          string
	DepositAsset  string
	DepositAmount int64
	WantAsset     string
	WantAmount    int64
	OfferTxid     string
	FulfillTxid   string
	CreatedAt     int64
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) error {
	_, err := q.db.ExecContext(ctx, insertTrade,
		arg.Pair,
		arg.DepositAsset,
		arg.DepositAmount,
		arg.WantAsset,
		arg.WantAmount,
		arg.OfferTxid,
		arg.FulfillTxid,
		arg.CreatedAt,
	)
	return err
}

const listPairs = `-- name: ListPairs :many
SELECT pair, min_amount, max_amount, base_decimals, quote_decimals, price_feed, invert_price FROM banco_pair
`

func (q *Queries) ListPairs(ctx context.Context) ([]BancoPair, error) {
	rows, err := q.db.QueryContext(ctx, listPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BancoPair
	for rows.Next() {
		var i BancoPair
		if err := rows.Scan(
			&i.Pair,
			&i.MinAmount,
			&i.MaxAmount,
			&i.BaseDecimals,
			&i.QuoteDecimals,
			&i.PriceFeed,
			&i.InvertPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
SELECT id, pair, deposit_asset, deposit_amount, want_asset, want_amount, offer_txid, fulfill_txid, created_at FROM trade ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListTrades(ctx context.Context, limit int64) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTrades, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Pair,
			&i.DepositAsset,
			&i.DepositAmount,
			&i.WantAsset,
			&i.WantAmount,
			&i.OfferTxid,
			&i.FulfillTxid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePair = `-- name: UpdatePair :execrows
UPDATE banco_pair
SET min_amount = ?, max_amount = ?, base_decimals = ?, quote_decimals = ?, price_feed = ?, invert_price = ?
WHERE pair = ?
`

type UpdatePairParams struct {
	MinAmount     int64
	MaxAmount     int64
	BaseDecimals  int64
	QuoteDecimals int64
	PriceFeed     string
	InvertPrice   int64
	Pair          string
}

func (q *Queries) UpdatePair(ctx context.Context, arg UpdatePairParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePair,
		arg.MinAmount,
		arg.MaxAmount,
		arg.BaseDecimals,
		arg.QuoteDecimals,
		arg.PriceFeed,
		arg.InvertPrice,
		arg.Pair,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
