name: ci_unit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: check linting
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.9.0

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: make test

      - name: Security Check
        uses: securego/gosec@v2.22.2
        with:
          args: '-no-fail -confidence medium -severity high -quiet -exclude-dir=.git -exclude-dir=vendor -exclude-generated ./...'
